### ISSUE TITLE
Dark mode flickers due to useEffect not running in MagicScriptTag component

### ISSUE THREAD

**Issue by zachweinberg** [brianlovin/brian-lovin-next#1070]
Hey love the website!

I believe the dark mode is flickering upon first load because the [Terser minification effect](https://github.com/brianlovin/brian-lovin-next/blob/604562d87f49c80c8a19bd5b6ea8d32f4fb4178d/src/components/Theme/InlineCssVariables.tsx#L37) of the script to populate CSS variables is never being run, so the magic script is never injected. A quick fix could just be loading the stringified function rather than minifying it in useEffect. Small performance hit but probably not too noticeable?

**Comment by brianlovin** [comment]
Oooh, good eye - I did recently start noticing the flicker again, but it hasn't always been like that, so definitely a regression. I'll test it out!

**Comment by zachweinberg** [comment]
Yea my pleasure!

**Comment by brianlovin** [comment]
Merged, I think that did the trick!
