### ISSUE TITLE
Remove `now.json` in favor of built-in env vars support

### ISSUE THREAD

**Issue by leerob** [brianlovin/brian-lovin-next#1362]
Hey 😄 You might already know this, but I figured I'd mention it. You can remove `now.json` entirely with environment variables support first-class [through dotenv in Next.js](https://nextjs.org/docs/basic-features/environment-variables). You can also remove `env` from `next.config.js`!

Also - Inside Vercel, you can [now more easily choose](https://vercel.com/docs/environment-variables) if your env var is a secret or plaintext.

**Comment by brianlovin** [comment]
I just have to go through and manually add all of these to my Vercel dashboard though, yeah? Or does having the secrets set already make this work out of the box? Right now I see this in the dashboard:

<img width="784" alt="Screen Shot 2021-03-08 at 10 09 07@2x" src="https://user-images.githubusercontent.com/1923260/110362620-57674480-7ff6-11eb-8917-5ac84106954b.png">

But of course I've already done `vercel secrets add ...` for each of the variables listed in the `now.json` file.

**Comment by leerob** [comment]
Convert - it's converting them from just secrets to env variables. When you select "secret", you'll be able to find all the existing secrets in the dropdown.

The biggest benefit is being able to run `vercel env pull .env.local` or a new machine and automatically set up your env, plus aligns with the best practices for env variables for those forking the repo 😄 

If you hit any issues, please let me know!

**Comment by brianlovin** [comment]
@leerob I just closed this after making the changes, but now I'm wondering: is there a best practice for using GitHub actions to run CI with whatever the `vercel dev` equivalent would be? I need Cypress to run with access to my environment variables, in a secure way of course.

**Comment by leerob** [comment]
👋  I would suggest running Cypress again the preview deployment URL. That's what we do at Vercel 😄

**Comment by brianlovin** [comment]
Oh wow, that's quite smart actually – any chance you are able to share or publish some of those action workflow files? Otherwise I can probably figure out how to string that together so things run in the correct order.
