### ISSUE TITLE
App Icons on the App Dissection page are throwing 404

### ISSUE THREAD

**Issue by cpintoval** [brianlovin/brian-lovin-next#1365]
**Description**
All images on the App Dissection page aren't being correctly loaded and the web app is throwing a 404 error when opened on the /app-dissection path. 

**Sample Error Generated in Console**
`Failed to load resource: the server responded with a status of 404 ()`
`GET https://brianlovin.com/_next/image?url=%2Fstatic%2Fimg%2Fapp-dissection%2Fpinterest-ios.jpeg&w=128&q=75 404`

See screencast below:
![404](https://user-images.githubusercontent.com/10165652/110505971-a97a9980-80cc-11eb-8a08-3660b385c80b.gif)

**Comment by brianlovin** [comment]
Thanks for the heads up! Should be fixed with a refresh 😊
