### ISSUE TITLE
How to replace books and music

### ISSUE THREAD

**Issue by Walter0807** [brianlovin/brian-lovin-next#174]
I wonder how to replace the contents. Should I do this line by line, or is there a convenient workflow? 

Really like the elegant design, appreciate it!

**Comment by brianlovin** [comment]
Yeah you just gotta do everything manually in `config/books.js` and `config/music.js` - not ideal flow right now, but it keeps the site more-or-less static and fast

**Comment by Walter0807** [comment]
Thanks!
