### ISSUE TITLE
Add OG tags for overthought posts.

### ISSUE THREAD

**Issue by leerob** [brianlovin/brian-lovin-next#375]
Hey 👋 

I noticed when trying to share your [latest blog post](https://brianlovin.com/overthought/investing-for-designers-and-developers) that it didn't have OG tags set up ([example](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fbrianlovin.com%2Foverthought%2Finvesting-for-designers-and-developers)).

You should be able to use something like [next-seo](https://www.npmjs.com/package/next-seo) on your [[slug].tsx](https://github.com/brianlovin/brian-lovin-next/blob/master/src/pages/overthought/%5Bslug%5D.tsx) page. I'm not sure the recommended way to do OG tags with Ghost, but I'm guessing it's something like this. 

```js
<NextSeo
  openGraph={{
    type: 'article',
    title: post.metaTitle,
    description: post.metaDescription,
    images: [
      {
        url: post.metaImage,
        width: 850,
        height: 650,
        alt: post.metaTitle,
      },
    ],
  }}
  title={post.metaTitle}
  description={post.metaDescription}
/>
```

Btw, nice use of TS 😍

**Comment by leerob** [comment]
After reading further into the code, I see you have next-seo! Maybe it's just missing from this file? 

I see it working here: https://github.com/brianlovin/brian-lovin-next/blob/7a1fd784475856eeabe0d5b48deb31e9685e05c4/src/pages/design-details/%5Bslug%5D.tsx#L24

**Comment by brianlovin** [comment]
@leerob thanks for the note, I must be missing it! I'll add it in.

Also, thank you for writing https://leerob.io/blog/mailchimp-next-js - it helped me implement https://github.com/brianlovin/brian-lovin-next/commit/ca3f7b7064ece68eb7033066c2f25c37737b5f25

**Comment by brianlovin** [comment]
Super weird, the tags are being set in the `<head>` - I can see them here: https://github.com/brianlovin/brian-lovin-next/blob/master/src/components/Overthought/Post/SEO.tsx

But the Sharing Debugger isn't picking them up...I wonder if it's an SSR thing.

**Comment by leerob** [comment]
I wonder if it's because you're returning `null` for the first SSR [here](https://github.com/brianlovin/brian-lovin-next/blob/master/src/components/Providers/index.tsx#L25) and then maybe the route is being cached? 

I ran into this [exact same issue](https://github.com/leerob/leerob.io/pull/130) with Next.js + styled-components + useDarkMode and ended up using your workaround. Let me see if the same issue is affecting me.

**Comment by leerob** [comment]
I think that's it. I [removed the workaround here](https://github.com/leerob/leerob.io/pull/132/commits/498a9521381bd7efcdc6fd5a184242c2e845248d) and it deployed that commit with Now. Looks like it [correctly picked up](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fleerob-git-2019-year-in-review.leerob1.now.sh%2F) the OG tags now.

What a bummer 😢 I have an issue open on styled-components for this: https://github.com/styled-components/styled-components/issues/2880

**Comment by brianlovin** [comment]
NOOO!

I think I know of a solution though: instead of returning `null` we could set a `visibility:hidden` property on the `body` of the page...testing.

**Comment by brianlovin** [comment]
Okay it doesn't work, and triggers the same issue that you pointed out in https://github.com/styled-components/styled-components/issues/2880

**Comment by leerob** [comment]
![](https://i.giphy.com/media/1wX9e0venWUkocJsXr/giphy.webp)

**Comment by brianlovin** [comment]
Hm this is frustrating. I'll see if I can get mxstbr to take a look.

**Comment by brianlovin** [comment]
This is a _very_ dumb hack, but instead of returning `null` you can do:

```javascript
// prevents ssr flash for mismatched dark mode
  if (!mounted) {
    return (
      <div style={{ visibility: 'hidden' }}>
        <Fathom>
          <Sentry>
          <SEO />
            <ThemeProvider theme={theme}>
              <GlobalStyles.ResetStyles />
              {children}
            </ThemeProvider>
          </Sentry>
        </Fathom>
      </div>
    )
  }
```

In combination with the `useEffect` and `useState` to re-render on mount, this seems to be working and I can verify that at least Twitter social cards are working on a test deployment.

**Comment by brianlovin** [comment]
Still unknown, we'll need to track this in the s-c issue above.
