### ISSUE TITLE
Disable horizontal textarea resizing

### ISSUE THREAD

**Issue by skrapkam** [brianlovin/brian-lovin-next#386]
https://github.com/brianlovin/brian-lovin-next/blob/88049b86bf98b85c8081aafdd17a7cc367e88e25/src/components/Overthought/Feedback/style.tsx#L42

Noticed that you're able to resize the textarea horizontally which can be a bit funky. Might be nicer to just have vertical resizing.

**Comment by brianlovin** [comment]
Fixed, thank you! https://github.com/brianlovin/brian-lovin-next/commit/b02ef6241162d08b7105c26115a93787966e74d7
