### ISSUE TITLE
How is the firebase store data structure?

### ISSUE THREAD

**Issue by inevity** [brianlovin/brian-lovin-next#501]
Just add bookmarks collection,and a doc with one url: https://xx. But give json error when access the /bookmarks

**Comment by inevity** [comment]
Or what should do to use the bookmarks feature?

**Comment by brianlovin** [comment]
Hey @inevity I don't have documentation up for the bookmarks feature, but yes it's all through Firebase. I built a separate app to post to Firebase, but there's no web functionality for it yet. The body for Twilio is just a URL right now :)

**Comment by inevity** [comment]
Thanks.
