### ISSUE TITLE
Avoid flash when use the default darkmode

### ISSUE THREAD

**Issue by inevity** [brianlovin/brian-lovin-next#536]
I  use your darkmode example to  your brian-lovin-next repo to avoid flash, but it  cannot work. So i switch to the https://raw.githubusercontent.com/donavon/use-dark-mode/develop/noflash.js.txt, and change the storagekey to not be default value avoding conflict with other website's keyname, also cannot avoid the flash.   Dont know why. 

Your site also flash when load the homepage.

**Comment by brianlovin** [comment]
Fixed in #627
