### ISSUE TITLE
Textarea on AMA page is resizeable beyond container

### ISSUE THREAD

**Issue by madebyankur** [brianlovin/brian-lovin-next#718]
I just noticed this on the AMA page and figured I should point it out. Also, proposed a possible fix for this in a PR, I hope that's ok: https://github.com/brianlovin/brian-lovin-next/pull/717

## Screenshot
![image](https://user-images.githubusercontent.com/12908185/83181319-ffc1b180-a124-11ea-8ce7-afc3ff13cedf.png)

**Comment by brianlovin** [comment]
Closed in #717
